# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://ghcr.io/cse210-team-5/feed-amalgamator/
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Directory
      run: mkdir configuration

    - name: Setup Config Files
      env:
        TEST_SECRET: ${{secrets.TEST_CONFIG}}
        APP_SECRET: ${{secrets.APP_CONFIG_PROD}}
      shell: bash
      run: |
        echo "$APP_SECRET" >> configuration/app_settings.ini
        echo "$TEST_SECRET" >> configuration/test_mastodon_client_info.ini

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ghcr.io/cse210-team-5/feed-amalgamator/feed-amalgamator:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'FeedAmalgamator'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9cda01e5ed4441acbb2bf60474ad5051 }}
        images: 'ghcr.io/cse210-team-5/feed-amalgamator/feed-amalgamator:${{ github.sha }}'
