---
name: lint
'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.5
      - name: Djlint Linting
        run: |
          pip install djlint
          djlint . --lint
      - name: Ruff Linting
        uses: chartboost/ruff-action@v1
      - name: Lint other files
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JSCPD: false
          VALIDATE_SQLFLUFF: false
          VALIDATE_HTML: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_GITLEAKS: false
          FILTER_REGEX_EXCLUDE: .*docs/.*
